### ISSUE TITLE
采用之后登不上教务网

### ISSUE THREAD

**Issue by ddgfd** [smd1121/ZJUAutoScoreQuery#1]
hello，学长，今天刚用了这个插件。感觉非常有效，但是使用中可能会存在一点小问题。
由于运行时间过长（基本在7-8分钟左右），频率稍微有点高（或许可以考虑改成半小时或一小时查询一次），导致现在会存在无法登录教务网的情况。

**Comment by smd1121** [comment]
其实是教务网崩了。。大家都登不了QWQ
